---
- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Upload Jenkins compose
  ansible.builtin.copy:
    src: /home/unknown/Videos/notyourjob/noob/Atlas-AI-Project-main/docker-compose.jenkins.yml
    dest: /app/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Upload Jenkins Dockerfile
  ansible.builtin.copy:
    src: /home/unknown/Videos/notyourjob/noob/Atlas-AI-Project-main/Dockerfile.jenkins
    dest: /app/Dockerfile.jenkins
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Build Jenkins image with python3
  ansible.builtin.shell: |
    cd /app
    docker compose build --no-cache
  become: yes
  become_user: ubuntu

- name: Deploy Jenkins
  ansible.builtin.shell: |
    cd /app
    docker compose down 2>/dev/null || true
    JENKINS_ADMIN_PASSWORD={{ vault_jenkins_admin_password }} docker compose up -d
  become: yes
  become_user: ubuntu
