[bastion]
bastion-host ansible_host=65.2.130.169 ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxel_devops_project.pem

[app]
app-server ansible_host=10.0.3.163 ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxel_devops_project.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /home/unknown/Documents/tkxel_devops_project.pem ubuntu@65.2.130.169"'

[jenkins]
jenkins-server ansible_host=10.0.3.50 ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxel_devops_project.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /home/unknown/Documents/tkxel_devops_project.pem ubuntu@65.2.130.169"'

[sonarqube]
sonarqube-server ansible_host=10.0.3.62 ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxel_devops_project.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /home/unknown/Documents/tkxel_devops_project.pem ubuntu@65.2.130.169"'

[monitoring]
monitoring-server ansible_host=10.0.3.129 ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxel_devops_project.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /home/unknown/Documents/tkxel_devops_project.pem ubuntu@65.2.130.169"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
